# Smart Gardening System Configuration

SOIL_DRY_THRESHOLD = 35
SOIL_WET_THRESHOLD = 75

TEMPERATURE_HIGH = 32
TEMPERATURE_LOW = 15

LIGHT_LOW_THRESHOLD = 30

# Pump operation
PUMP_DURATION_SECONDS = 5

# Sensor simulation limits
MIN_SOIL_MOISTURE = 0
MAX_SOIL_MOISTURE = 100

MIN_HUMIDITY = 0
MAX_HUMIDITY = 100

MIN_LIGHT = 0
MAX_LIGHT = 100